name: ✨ Feature Request
description: Suggest an idea or enhancement for Origami CLI
title: "[Feature]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing ideas to improve **Origami**! Please describe your feature clearly so we can understand how it benefits the project.

  - type: input
    id: feature_title
    attributes:
      label: Feature Summary
      description: Brief one-line title of the feature or enhancement
      placeholder: e.g., "Allow custom JVM args per profile"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: What do you want to add or change? How should it behave?
      placeholder: Describe the functionality in detail...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature needed?
      description: What problem does it solve or improve for you or other users?
      placeholder: Explain why this would be useful...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives or workarounds
      description: Have you tried any alternatives? Why are they not ideal?
      placeholder: Mention other options or things you've tried...

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any related mods, versions, screenshots, or links?
